# Generated by Django 6.0.3 on 2026-04-10 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_assignment_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.classroom'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'assignment')},
        ),
    ]
