# Generated by Django 6.0.3 on 2026-04-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_assignment_classroom_alter_grade_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_missing',
            field=models.BooleanField(default=False),
        ),
    ]
