# Generated by Django 6.0.3 on 2026-04-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_grade_is_missing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='points_earned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
